import style from "./styles/Layout.module.css";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { CiMenuKebab } from "react-icons/ci";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showSlideMenu, setShowSlideMenu] = useState(false);

  const showOrHideSlideMenuOnClick = () => {
    !showSlideMenu ? setShowSlideMenu(true) : setShowSlideMenu(false);
  };
  return (
    <div className={style.containLayout}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="xd" />
        <title>BT Transfer</title>
      </Head>
      <nav className={style.containNav}>
        <button
          className={style.buttonMenu}
          onClick={showOrHideSlideMenuOnClick}
        >
          <CiMenuKebab className={style.iconMenu} />
        </button>
        {showSlideMenu && (
          <div id="slide-options" className={style.containSlideOptions}>
            <Link className={style.btnSlideOptions} href="api/auth/logout">
              Cerrar Sesion
            </Link>
          </div>
        )}
        <span className={style.simbolToDo}>ToDo</span>
      </nav>
      {children}
    </div>
  );
}
